apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: Vijaygawate/gitops01:88db3cf8a6e506bce6b5cb1fb3b1661d93026cab
          imagePullPolicy: Always
          ports:
            - containerPort: 80
